window.DISTRICT_META = {
  central: {
    name: 'Центральный федеральный округ',
    shortName: 'ЦФО',
    color: '#8b7740',
    tint: '#3f3927',
    summary:
      'Высокая плотность гарнизонов, штабных подразделений и учебно-логистических площадок.',
    profile: 'Штабной, учебный и тыловой контур',
    hub: 'Москва'
  },
  northwestern: {
    name: 'Северо-Западный федеральный округ',
    shortName: 'СЗФО',
    color: '#65775a',
    tint: '#273126',
    summary:
      'Округ с арктическими и морскими направлениями, усиленной логистикой портовых узлов.',
    profile: 'Морской и арктический контур',
    hub: 'Санкт-Петербург'
  },
  southern: {
    name: 'Южный федеральный округ',
    shortName: 'ЮФО',
    color: '#8c6544',
    tint: '#382921',
    summary:
      'Южное направление с высокой транспортной связанностью и опорой на аэромобильные узлы.',
    profile: 'Мобильные силы и транспортные коридоры',
    hub: 'Ростов-на-Дону'
  },
  'north-caucasian': {
    name: 'Северо-Кавказский федеральный округ',
    shortName: 'СКФО',
    color: '#7a6148',
    tint: '#342820',
    summary:
      'Горный рельеф, концентрация учебных полигонов и подразделений оперативного реагирования.',
    profile: 'Горная подготовка и оперативный резерв',
    hub: 'Пятигорск'
  },
  volga: {
    name: 'Приволжский федеральный округ',
    shortName: 'ПФО',
    color: '#6d7154',
    tint: '#2d3024',
    summary:
      'Крупная сеть промышленных и ремонтных центров, соединяющих западный и восточный контур.',
    profile: 'Промышленный и ремонтный пояс',
    hub: 'Нижний Новгород'
  },
  ural: {
    name: 'Уральский федеральный округ',
    shortName: 'УрФО',
    color: '#566b58',
    tint: '#223028',
    summary:
      'Стратегический тыловой узел с сильной производственной базой и северной логистикой.',
    profile: 'Стратегический тыл и северная логистика',
    hub: 'Екатеринбург'
  },
  siberian: {
    name: 'Сибирский федеральный округ',
    shortName: 'СФО',
    color: '#607363',
    tint: '#253028',
    summary:
      'Протяженный контур внутренних коммуникаций, авиационной поддержки и полигонной подготовки.',
    profile: 'Авиация, полигоны и длинные плечи снабжения',
    hub: 'Новосибирск'
  },
  'far-eastern': {
    name: 'Дальневосточный федеральный округ',
    shortName: 'ДФО',
    color: '#86674c',
    tint: '#372b22',
    summary:
      'Округ с океанским и тихоокеанским плечом, распределенными гарнизонами и удаленными базами.',
    profile: 'Океанское направление и распределенные базы',
    hub: 'Владивосток'
  }
};

window.UNITS_DATA = [
  {
    id: '10001',
    name: 'в/ч 10001',
    districtKey: 'central',
    district: 'Центральный федеральный округ',
    city: 'Москва',
    lat: 55.7558,
    lng: 37.6176,
    garrison: 'Московский гарнизон',
    specialization: 'штабная координация',
    prosecutor: 'Военная прокуратура Московского гарнизона',
    curatorRank: 'полковник юстиции',
    curatorName: 'Александр Воронцов',
    phone: '+7 (495) 410-18-27',
    personnel: 1320,
    readiness: 94,
    status: 'стабильный режим',
    lastInspection: '14.02.2026'
  },
  {
    id: '10002',
    name: 'в/ч 10002',
    districtKey: 'central',
    district: 'Центральный федеральный округ',
    city: 'Тула',
    lat: 54.1961,
    lng: 37.6182,
    garrison: 'Тульский гарнизон',
    specialization: 'артиллерийское обеспечение',
    prosecutor: 'Военная прокуратура Тульского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Илья Гаврилов',
    phone: '+7 (4872) 52-17-44',
    personnel: 870,
    readiness: 87,
    status: 'плановая подготовка',
    lastInspection: '03.03.2026'
  },
  {
    id: '10003',
    name: 'в/ч 10003',
    districtKey: 'central',
    district: 'Центральный федеральный округ',
    city: 'Воронеж',
    lat: 51.6608,
    lng: 39.2003,
    garrison: 'Воронежский гарнизон',
    specialization: 'авиационно-техническая поддержка',
    prosecutor: 'Военная прокуратура Воронежского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Дмитрий Антонов',
    phone: '+7 (473) 255-63-11',
    personnel: 940,
    readiness: 82,
    status: 'плановая подготовка',
    lastInspection: '21.01.2026'
  },
  {
    id: '10004',
    name: 'в/ч 10004',
    districtKey: 'central',
    district: 'Центральный федеральный округ',
    city: 'Ярославль',
    lat: 57.6261,
    lng: 39.8845,
    garrison: 'Ярославский гарнизон',
    specialization: 'радиотехническое сопровождение',
    prosecutor: 'Военная прокуратура Ярославского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Максим Лапин',
    phone: '+7 (4852) 49-20-38',
    personnel: 760,
    readiness: 85,
    status: 'стабильный режим',
    lastInspection: '10.02.2026'
  },
  {
    id: '10005',
    name: 'в/ч 10005',
    districtKey: 'central',
    district: 'Центральный федеральный округ',
    city: 'Брянск',
    lat: 53.2436,
    lng: 34.3634,
    garrison: 'Брянский гарнизон',
    specialization: 'тыловое снабжение',
    prosecutor: 'Военная прокуратура Брянского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Роман Белов',
    phone: '+7 (4832) 41-55-09',
    personnel: 680,
    readiness: 79,
    status: 'усиленный контроль',
    lastInspection: '27.02.2026'
  },
  {
    id: '20001',
    name: 'в/ч 20001',
    districtKey: 'northwestern',
    district: 'Северо-Западный федеральный округ',
    city: 'Санкт-Петербург',
    lat: 59.9311,
    lng: 30.3609,
    garrison: 'Санкт-Петербургский гарнизон',
    specialization: 'морская координация',
    prosecutor: 'Военная прокуратура Санкт-Петербургского гарнизона',
    curatorRank: 'полковник юстиции',
    curatorName: 'Лев Фомин',
    phone: '+7 (812) 514-33-26',
    personnel: 1180,
    readiness: 92,
    status: 'стабильный режим',
    lastInspection: '18.02.2026'
  },
  {
    id: '20002',
    name: 'в/ч 20002',
    districtKey: 'northwestern',
    district: 'Северо-Западный федеральный округ',
    city: 'Калининград',
    lat: 54.7104,
    lng: 20.4522,
    garrison: 'Калининградский гарнизон',
    specialization: 'береговая оборона',
    prosecutor: 'Военная прокуратура Калининградского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Егор Нестеров',
    phone: '+7 (4012) 61-42-87',
    personnel: 910,
    readiness: 90,
    status: 'повышенная готовность',
    lastInspection: '01.03.2026'
  },
  {
    id: '20003',
    name: 'в/ч 20003',
    districtKey: 'northwestern',
    district: 'Северо-Западный федеральный округ',
    city: 'Мурманск',
    lat: 68.9585,
    lng: 33.0827,
    garrison: 'Мурманский гарнизон',
    specialization: 'арктическая логистика',
    prosecutor: 'Военная прокуратура Мурманского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Тимур Головин',
    phone: '+7 (8152) 44-28-35',
    personnel: 840,
    readiness: 88,
    status: 'стабильный режим',
    lastInspection: '12.01.2026'
  },
  {
    id: '20004',
    name: 'в/ч 20004',
    districtKey: 'northwestern',
    district: 'Северо-Западный федеральный округ',
    city: 'Архангельск',
    lat: 64.5393,
    lng: 40.5187,
    garrison: 'Архангельский гарнизон',
    specialization: 'транспортная разгрузка',
    prosecutor: 'Военная прокуратура Архангельского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Никита Ершов',
    phone: '+7 (8182) 57-10-46',
    personnel: 650,
    readiness: 81,
    status: 'плановая подготовка',
    lastInspection: '05.02.2026'
  },
  {
    id: '20005',
    name: 'в/ч 20005',
    districtKey: 'northwestern',
    district: 'Северо-Западный федеральный округ',
    city: 'Петрозаводск',
    lat: 61.7891,
    lng: 34.3596,
    garrison: 'Карельский гарнизон',
    specialization: 'учебный центр связи',
    prosecutor: 'Военная прокуратура Карельского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Олег Савин',
    phone: '+7 (8142) 33-94-12',
    personnel: 540,
    readiness: 78,
    status: 'усиленный контроль',
    lastInspection: '23.02.2026'
  },
  {
    id: '30001',
    name: 'в/ч 30001',
    districtKey: 'southern',
    district: 'Южный федеральный округ',
    city: 'Ростов-на-Дону',
    lat: 47.2357,
    lng: 39.7015,
    garrison: 'Ростовский гарнизон',
    specialization: 'оперативное управление',
    prosecutor: 'Военная прокуратура Ростовского гарнизона',
    curatorRank: 'полковник юстиции',
    curatorName: 'Павел Медведев',
    phone: '+7 (863) 231-17-92',
    personnel: 1250,
    readiness: 93,
    status: 'повышенная готовность',
    lastInspection: '08.03.2026'
  },
  {
    id: '30002',
    name: 'в/ч 30002',
    districtKey: 'southern',
    district: 'Южный федеральный округ',
    city: 'Волгоград',
    lat: 48.7071,
    lng: 44.5169,
    garrison: 'Волгоградский гарнизон',
    specialization: 'инженерная подготовка',
    prosecutor: 'Военная прокуратура Волгоградского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Антон Мартынов',
    phone: '+7 (8442) 45-12-39',
    personnel: 760,
    readiness: 84,
    status: 'стабильный режим',
    lastInspection: '15.01.2026'
  },
  {
    id: '30003',
    name: 'в/ч 30003',
    districtKey: 'southern',
    district: 'Южный федеральный округ',
    city: 'Краснодар',
    lat: 45.0355,
    lng: 38.9753,
    garrison: 'Краснодарский гарнизон',
    specialization: 'автомобильное снабжение',
    prosecutor: 'Военная прокуратура Краснодарского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Игорь Самойлов',
    phone: '+7 (861) 268-27-41',
    personnel: 720,
    readiness: 83,
    status: 'плановая подготовка',
    lastInspection: '19.02.2026'
  },
  {
    id: '30004',
    name: 'в/ч 30004',
    districtKey: 'southern',
    district: 'Южный федеральный округ',
    city: 'Астрахань',
    lat: 46.3497,
    lng: 48.0408,
    garrison: 'Астраханский гарнизон',
    specialization: 'береговое сопровождение',
    prosecutor: 'Военная прокуратура Астраханского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Глеб Фролов',
    phone: '+7 (8512) 62-34-50',
    personnel: 610,
    readiness: 80,
    status: 'стабильный режим',
    lastInspection: '24.02.2026'
  },
  {
    id: '30005',
    name: 'в/ч 30005',
    districtKey: 'southern',
    district: 'Южный федеральный округ',
    city: 'Элиста',
    lat: 46.3077,
    lng: 44.2558,
    garrison: 'Каспийский гарнизон',
    specialization: 'мобильный резерв',
    prosecutor: 'Военная прокуратура Каспийского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Степан Прохоров',
    phone: '+7 (84722) 5-88-31',
    personnel: 530,
    readiness: 76,
    status: 'усиленный контроль',
    lastInspection: '11.02.2026'
  },
  {
    id: '40001',
    name: 'в/ч 40001',
    districtKey: 'north-caucasian',
    district: 'Северо-Кавказский федеральный округ',
    city: 'Пятигорск',
    lat: 44.0486,
    lng: 43.0594,
    garrison: 'Пятигорский гарнизон',
    specialization: 'оперативный резерв',
    prosecutor: 'Военная прокуратура Пятигорского гарнизона',
    curatorRank: 'полковник юстиции',
    curatorName: 'Виктор Харитонов',
    phone: '+7 (8793) 38-14-60',
    personnel: 860,
    readiness: 91,
    status: 'повышенная готовность',
    lastInspection: '06.03.2026'
  },
  {
    id: '40002',
    name: 'в/ч 40002',
    districtKey: 'north-caucasian',
    district: 'Северо-Кавказский федеральный округ',
    city: 'Ставрополь',
    lat: 45.0445,
    lng: 41.969,
    garrison: 'Ставропольский гарнизон',
    specialization: 'учебный полигон',
    prosecutor: 'Военная прокуратура Ставропольского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Константин Жуков',
    phone: '+7 (8652) 57-16-08',
    personnel: 770,
    readiness: 86,
    status: 'стабильный режим',
    lastInspection: '17.02.2026'
  },
  {
    id: '40003',
    name: 'в/ч 40003',
    districtKey: 'north-caucasian',
    district: 'Северо-Кавказский федеральный округ',
    city: 'Махачкала',
    lat: 42.9849,
    lng: 47.5047,
    garrison: 'Махачкалинский гарнизон',
    specialization: 'береговое наблюдение',
    prosecutor: 'Военная прокуратура Махачкалинского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Руслан Алиев',
    phone: '+7 (8722) 66-49-72',
    personnel: 690,
    readiness: 82,
    status: 'усиленный контроль',
    lastInspection: '25.01.2026'
  },
  {
    id: '40004',
    name: 'в/ч 40004',
    districtKey: 'north-caucasian',
    district: 'Северо-Кавказский федеральный округ',
    city: 'Нальчик',
    lat: 43.4845,
    lng: 43.6071,
    garrison: 'Нальчикский гарнизон',
    specialization: 'горная подготовка',
    prosecutor: 'Военная прокуратура Нальчикского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Сергей Кошелев',
    phone: '+7 (8662) 41-82-15',
    personnel: 580,
    readiness: 88,
    status: 'стабильный режим',
    lastInspection: '04.02.2026'
  },
  {
    id: '40005',
    name: 'в/ч 40005',
    districtKey: 'north-caucasian',
    district: 'Северо-Кавказский федеральный округ',
    city: 'Владикавказ',
    lat: 43.0241,
    lng: 44.6819,
    garrison: 'Владикавказский гарнизон',
    specialization: 'горно-стрелковая поддержка',
    prosecutor: 'Военная прокуратура Владикавказского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Марат Григорьев',
    phone: '+7 (8672) 54-33-29',
    personnel: 610,
    readiness: 84,
    status: 'плановая подготовка',
    lastInspection: '22.02.2026'
  },
  {
    id: '50001',
    name: 'в/ч 50001',
    districtKey: 'volga',
    district: 'Приволжский федеральный округ',
    city: 'Нижний Новгород',
    lat: 56.3269,
    lng: 44.0065,
    garrison: 'Нижегородский гарнизон',
    specialization: 'ремонтно-технический центр',
    prosecutor: 'Военная прокуратура Нижегородского гарнизона',
    curatorRank: 'полковник юстиции',
    curatorName: 'Андрей Мельник',
    phone: '+7 (831) 428-62-14',
    personnel: 980,
    readiness: 89,
    status: 'стабильный режим',
    lastInspection: '16.02.2026'
  },
  {
    id: '50002',
    name: 'в/ч 50002',
    districtKey: 'volga',
    district: 'Приволжский федеральный округ',
    city: 'Казань',
    lat: 55.7961,
    lng: 49.1064,
    garrison: 'Казанский гарнизон',
    specialization: 'связь и навигация',
    prosecutor: 'Военная прокуратура Казанского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Ильдар Кадыров',
    phone: '+7 (843) 221-30-77',
    personnel: 790,
    readiness: 86,
    status: 'стабильный режим',
    lastInspection: '07.03.2026'
  },
  {
    id: '50003',
    name: 'в/ч 50003',
    districtKey: 'volga',
    district: 'Приволжский федеральный округ',
    city: 'Самара',
    lat: 53.1959,
    lng: 50.1008,
    garrison: 'Самарский гарнизон',
    specialization: 'авиационное снабжение',
    prosecutor: 'Военная прокуратура Самарского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Николай Горюнов',
    phone: '+7 (846) 300-18-44',
    personnel: 830,
    readiness: 83,
    status: 'плановая подготовка',
    lastInspection: '13.01.2026'
  },
  {
    id: '50004',
    name: 'в/ч 50004',
    districtKey: 'volga',
    district: 'Приволжский федеральный округ',
    city: 'Уфа',
    lat: 54.7388,
    lng: 55.9721,
    garrison: 'Уфимский гарнизон',
    specialization: 'тыловое хранение',
    prosecutor: 'Военная прокуратура Уфимского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Артур Синицын',
    phone: '+7 (347) 284-71-25',
    personnel: 690,
    readiness: 81,
    status: 'усиленный контроль',
    lastInspection: '20.02.2026'
  },
  {
    id: '50005',
    name: 'в/ч 50005',
    districtKey: 'volga',
    district: 'Приволжский федеральный округ',
    city: 'Пермь',
    lat: 58.0105,
    lng: 56.2502,
    garrison: 'Пермский гарнизон',
    specialization: 'учебно-ремонтная база',
    prosecutor: 'Военная прокуратура Пермского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Владимир Голубев',
    phone: '+7 (342) 214-09-56',
    personnel: 640,
    readiness: 80,
    status: 'плановая подготовка',
    lastInspection: '29.02.2026'
  },
  {
    id: '60001',
    name: 'в/ч 60001',
    districtKey: 'central',
    district: 'Центральный федеральный округ',
    city: 'Смоленск',
    lat: 54.7826,
    lng: 32.0453,
    garrison: 'Смоленский гарнизон',
    specialization: 'оперативное координационное подразделение',
    prosecutor: 'Военная прокуратура Смоленского гарнизона',
    rank: 'Полковник юстиции',
    fio: 'Борисов Анатолий Викторович',
    curatorRank: 'полковник юстиции',
    curatorName: 'Борисов Анатолий Викторович',
    phone: '+7 (4812) 38-45-67',
    personnel: 1110,
    readiness: 90,
    status: 'стабильный режим',
    lastInspection: '09.03.2026'
  },
  {
    id: '60002',
    name: 'в/ч 60002',
    districtKey: 'ural',
    district: 'Уральский федеральный округ',
    city: 'Челябинск',
    lat: 55.1604,
    lng: 61.4026,
    garrison: 'Челябинский гарнизон',
    specialization: 'бронетанковый ремонт',
    prosecutor: 'Военная прокуратура Челябинского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Евгений Пугачев',
    phone: '+7 (351) 245-61-77',
    personnel: 870,
    readiness: 85,
    status: 'стабильный режим',
    lastInspection: '28.02.2026'
  },
  {
    id: '60003',
    name: 'в/ч 60003',
    districtKey: 'ural',
    district: 'Уральский федеральный округ',
    city: 'Тюмень',
    lat: 57.153,
    lng: 65.5343,
    garrison: 'Тюменский гарнизон',
    specialization: 'транспортный хаб',
    prosecutor: 'Военная прокуратура Тюменского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Илья Ушаков',
    phone: '+7 (3452) 49-13-62',
    personnel: 710,
    readiness: 82,
    status: 'плановая подготовка',
    lastInspection: '30.01.2026'
  },
  {
    id: '60004',
    name: 'в/ч 60004',
    districtKey: 'ural',
    district: 'Уральский федеральный округ',
    city: 'Сургут',
    lat: 61.254,
    lng: 73.3962,
    garrison: 'Северный гарнизон Сургута',
    specialization: 'северное снабжение',
    prosecutor: 'Военная прокуратура Северного гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Артем Беспалов',
    phone: '+7 (3462) 71-04-19',
    personnel: 620,
    readiness: 79,
    status: 'усиленный контроль',
    lastInspection: '12.02.2026'
  },
  {
    id: '60005',
    name: 'в/ч 60005',
    districtKey: 'ural',
    district: 'Уральский федеральный округ',
    city: 'Салехард',
    lat: 66.53,
    lng: 66.6019,
    garrison: 'Ямальский гарнизон',
    specialization: 'арктический резерв',
    prosecutor: 'Военная прокуратура Ямальского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Рустам Плотников',
    phone: '+7 (34922) 4-77-14',
    personnel: 490,
    readiness: 77,
    status: 'плановая подготовка',
    lastInspection: '17.01.2026'
  },
  {
    id: '70001',
    name: 'в/ч 70001',
    districtKey: 'siberian',
    district: 'Сибирский федеральный округ',
    city: 'Новосибирск',
    lat: 55.0084,
    lng: 82.9357,
    garrison: 'Новосибирский гарнизон',
    specialization: 'авиационный узел',
    prosecutor: 'Военная прокуратура Новосибирского гарнизона',
    curatorRank: 'полковник юстиции',
    curatorName: 'Алексей Селиванов',
    phone: '+7 (383) 227-81-13',
    personnel: 1020,
    readiness: 91,
    status: 'стабильный режим',
    lastInspection: '02.03.2026'
  },
  {
    id: '70002',
    name: 'в/ч 70002',
    districtKey: 'siberian',
    district: 'Сибирский федеральный округ',
    city: 'Омск',
    lat: 54.9885,
    lng: 73.3242,
    garrison: 'Омский гарнизон',
    specialization: 'бронетанковое обеспечение',
    prosecutor: 'Военная прокуратура Омского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Вадим Рябов',
    phone: '+7 (3812) 66-32-51',
    personnel: 860,
    readiness: 86,
    status: 'стабильный режим',
    lastInspection: '11.03.2026'
  },
  {
    id: '70003',
    name: 'в/ч 70003',
    districtKey: 'siberian',
    district: 'Сибирский федеральный округ',
    city: 'Красноярск',
    lat: 56.0184,
    lng: 92.8672,
    garrison: 'Красноярский гарнизон',
    specialization: 'учебный полигон',
    prosecutor: 'Военная прокуратура Красноярского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Станислав Крылов',
    phone: '+7 (391) 229-14-65',
    personnel: 780,
    readiness: 82,
    status: 'плановая подготовка',
    lastInspection: '26.02.2026'
  },
  {
    id: '70004',
    name: 'в/ч 70004',
    districtKey: 'siberian',
    district: 'Сибирский федеральный округ',
    city: 'Иркутск',
    lat: 52.2869,
    lng: 104.305,
    garrison: 'Иркутский гарнизон',
    specialization: 'дальнее снабжение',
    prosecutor: 'Военная прокуратура Иркутского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Егор Князев',
    phone: '+7 (3952) 53-67-28',
    personnel: 700,
    readiness: 80,
    status: 'усиленный контроль',
    lastInspection: '08.02.2026'
  },
  {
    id: '70005',
    name: 'в/ч 70005',
    districtKey: 'siberian',
    district: 'Сибирский федеральный округ',
    city: 'Кемерово',
    lat: 55.3552,
    lng: 86.0872,
    garrison: 'Кемеровский гарнизон',
    specialization: 'резерв хранения',
    prosecutor: 'Военная прокуратура Кемеровского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Олег Кирьянов',
    phone: '+7 (3842) 42-18-97',
    personnel: 590,
    readiness: 78,
    status: 'плановая подготовка',
    lastInspection: '01.02.2026'
  },
  {
    id: '80001',
    name: 'в/ч 80001',
    districtKey: 'far-eastern',
    district: 'Дальневосточный федеральный округ',
    city: 'Владивосток',
    lat: 43.1155,
    lng: 131.8855,
    garrison: 'Владивостокский гарнизон',
    specialization: 'тихоокеанская координация',
    prosecutor: 'Военная прокуратура Владивостокского гарнизона',
    curatorRank: 'полковник юстиции',
    curatorName: 'Кирилл Демин',
    phone: '+7 (423) 249-33-16',
    personnel: 1280,
    readiness: 95,
    status: 'повышенная готовность',
    lastInspection: '05.03.2026'
  },
  {
    id: '80002',
    name: 'в/ч 80002',
    districtKey: 'far-eastern',
    district: 'Дальневосточный федеральный округ',
    city: 'Хабаровск',
    lat: 48.4802,
    lng: 135.0719,
    garrison: 'Хабаровский гарнизон',
    specialization: 'оперативное снабжение',
    prosecutor: 'Военная прокуратура Хабаровского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Андрей Ульянов',
    phone: '+7 (4212) 60-55-20',
    personnel: 870,
    readiness: 88,
    status: 'стабильный режим',
    lastInspection: '24.01.2026'
  },
  {
    id: '80003',
    name: 'в/ч 80003',
    districtKey: 'far-eastern',
    district: 'Дальневосточный федеральный округ',
    city: 'Южно-Сахалинск',
    lat: 46.9591,
    lng: 142.738,
    garrison: 'Сахалинский гарнизон',
    specialization: 'островная логистика',
    prosecutor: 'Военная прокуратура Сахалинского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Виталий Баранов',
    phone: '+7 (4242) 42-77-61',
    personnel: 610,
    readiness: 84,
    status: 'стабильный режим',
    lastInspection: '19.01.2026'
  },
  {
    id: '80004',
    name: 'в/ч 80004',
    districtKey: 'far-eastern',
    district: 'Дальневосточный федеральный округ',
    city: 'Якутск',
    lat: 62.0281,
    lng: 129.7326,
    garrison: 'Якутский гарнизон',
    specialization: 'северный авиаузел',
    prosecutor: 'Военная прокуратура Якутского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Денис Климов',
    phone: '+7 (4112) 31-64-55',
    personnel: 560,
    readiness: 79,
    status: 'усиленный контроль',
    lastInspection: '09.02.2026'
  },
  {
    id: '80005',
    name: 'в/ч 80005',
    districtKey: 'far-eastern',
    district: 'Дальневосточный федеральный округ',
    city: 'Петропавловск-Камчатский',
    lat: 53.037,
    lng: 158.656,
    garrison: 'Камчатский гарнизон',
    specialization: 'удаленная береговая база',
    prosecutor: 'Военная прокуратура Камчатского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Матвей Соболев',
    phone: '+7 (4152) 26-44-83',
    personnel: 520,
    readiness: 81,
    status: 'плановая подготовка',
    lastInspection: '14.01.2026'
  }
];

window.UNITS_DATA.push(
  {
    id: '10006',
    name: 'в/ч 10006',
    districtKey: 'central',
    district: 'Центральный федеральный округ',
    city: 'Курск',
    lat: 51.7304,
    lng: 36.1926,
    garrison: 'Курский гарнизон',
    specialization: 'ремонтно-восстановительная база',
    prosecutor: 'Военная прокуратура Курского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Сергей Нечаев',
    phone: '+7 (4712) 44-29-70',
    personnel: 640,
    readiness: 81,
    status: 'стабильный режим',
    lastInspection: '06.02.2026'
  },
  {
    id: '10007',
    name: 'в/ч 10007',
    districtKey: 'central',
    district: 'Центральный федеральный округ',
    city: 'Липецк',
    lat: 52.6088,
    lng: 39.5992,
    garrison: 'Липецкий гарнизон',
    specialization: 'учебный авиационный центр',
    prosecutor: 'Военная прокуратура Липецкого гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Георгий Серов',
    phone: '+7 (4742) 31-87-22',
    personnel: 720,
    readiness: 86,
    status: 'плановая подготовка',
    lastInspection: '28.02.2026'
  },
  {
    id: '20006',
    name: 'в/ч 20006',
    districtKey: 'northwestern',
    district: 'Северо-Западный федеральный округ',
    city: 'Псков',
    lat: 57.8194,
    lng: 28.3318,
    garrison: 'Псковский гарнизон',
    specialization: 'десантное сопровождение',
    prosecutor: 'Военная прокуратура Псковского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Артем Аксенов',
    phone: '+7 (8112) 67-13-44',
    personnel: 690,
    readiness: 87,
    status: 'стабильный режим',
    lastInspection: '07.03.2026'
  },
  {
    id: '20007',
    name: 'в/ч 20007',
    districtKey: 'northwestern',
    district: 'Северо-Западный федеральный округ',
    city: 'Северодвинск',
    lat: 64.5635,
    lng: 39.8302,
    garrison: 'Северодвинский гарнизон',
    specialization: 'судоремонтное сопровождение',
    prosecutor: 'Военная прокуратура Северодвинского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Владислав Титов',
    phone: '+7 (8184) 58-21-36',
    personnel: 620,
    readiness: 84,
    status: 'плановая подготовка',
    lastInspection: '20.01.2026'
  },
  {
    id: '30006',
    name: 'в/ч 30006',
    districtKey: 'southern',
    district: 'Южный федеральный округ',
    city: 'Новороссийск',
    lat: 44.7235,
    lng: 37.7686,
    garrison: 'Новороссийский гарнизон',
    specialization: 'портовое снабжение',
    prosecutor: 'Военная прокуратура Новороссийского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Леонид Абрамов',
    phone: '+7 (8617) 62-14-38',
    personnel: 710,
    readiness: 88,
    status: 'повышенная готовность',
    lastInspection: '04.03.2026'
  },
  {
    id: '30007',
    name: 'в/ч 30007',
    districtKey: 'southern',
    district: 'Южный федеральный округ',
    city: 'Севастополь',
    lat: 44.6166,
    lng: 33.5254,
    garrison: 'Севастопольский гарнизон',
    specialization: 'береговое командование',
    prosecutor: 'Военная прокуратура Севастопольского гарнизона',
    curatorRank: 'полковник юстиции',
    curatorName: 'Денис Королев',
    phone: '+7 (8692) 44-91-12',
    personnel: 960,
    readiness: 92,
    status: 'повышенная готовность',
    lastInspection: '09.03.2026'
  },
  {
    id: '40006',
    name: 'в/ч 40006',
    districtKey: 'north-caucasian',
    district: 'Северо-Кавказский федеральный округ',
    city: 'Грозный',
    lat: 43.3178,
    lng: 45.6949,
    garrison: 'Грозненский гарнизон',
    specialization: 'оперативная связь',
    prosecutor: 'Военная прокуратура Грозненского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Азамат Елкин',
    phone: '+7 (8712) 28-53-47',
    personnel: 620,
    readiness: 83,
    status: 'усиленный контроль',
    lastInspection: '11.02.2026'
  },
  {
    id: '40007',
    name: 'в/ч 40007',
    districtKey: 'north-caucasian',
    district: 'Северо-Кавказский федеральный округ',
    city: 'Дербент',
    lat: 42.0589,
    lng: 48.2909,
    garrison: 'Дербентский гарнизон',
    specialization: 'береговой учебный центр',
    prosecutor: 'Военная прокуратура Дербентского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Тамерлан Исаев',
    phone: '+7 (87240) 4-14-61',
    personnel: 540,
    readiness: 79,
    status: 'плановая подготовка',
    lastInspection: '18.01.2026'
  },
  {
    id: '50006',
    name: 'в/ч 50006',
    districtKey: 'volga',
    district: 'Приволжский федеральный округ',
    city: 'Саратов',
    lat: 51.5336,
    lng: 46.0343,
    garrison: 'Саратовский гарнизон',
    specialization: 'ракетно-техническое обеспечение',
    prosecutor: 'Военная прокуратура Саратовского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Александр Носов',
    phone: '+7 (8452) 55-32-80',
    personnel: 760,
    readiness: 85,
    status: 'стабильный режим',
    lastInspection: '03.03.2026'
  },
  {
    id: '50007',
    name: 'в/ч 50007',
    districtKey: 'volga',
    district: 'Приволжский федеральный округ',
    city: 'Оренбург',
    lat: 51.7682,
    lng: 55.0969,
    garrison: 'Оренбургский гарнизон',
    specialization: 'учебный центр обеспечения',
    prosecutor: 'Военная прокуратура Оренбургского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Евгений Савчук',
    phone: '+7 (3532) 47-10-28',
    personnel: 610,
    readiness: 80,
    status: 'плановая подготовка',
    lastInspection: '22.02.2026'
  },
  {
    id: '60006',
    name: 'в/ч 60006',
    districtKey: 'ural',
    district: 'Уральский федеральный округ',
    city: 'Нижневартовск',
    lat: 60.9398,
    lng: 76.5696,
    garrison: 'Нижневартовский гарнизон',
    specialization: 'северный складской узел',
    prosecutor: 'Военная прокуратура Нижневартовского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Олег Громов',
    phone: '+7 (3466) 48-16-04',
    personnel: 540,
    readiness: 78,
    status: 'усиленный контроль',
    lastInspection: '16.02.2026'
  },
  {
    id: '60007',
    name: 'в/ч 60007',
    districtKey: 'ural',
    district: 'Уральский федеральный округ',
    city: 'Курган',
    lat: 55.4444,
    lng: 65.3161,
    garrison: 'Курганский гарнизон',
    specialization: 'ремонт бронетехники',
    prosecutor: 'Военная прокуратура Курганского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Игорь Варламов',
    phone: '+7 (3522) 52-66-31',
    personnel: 680,
    readiness: 82,
    status: 'стабильный режим',
    lastInspection: '12.03.2026'
  },
  {
    id: '70006',
    name: 'в/ч 70006',
    districtKey: 'siberian',
    district: 'Сибирский федеральный округ',
    city: 'Томск',
    lat: 56.501,
    lng: 84.9925,
    garrison: 'Томский гарнизон',
    specialization: 'центр связи и аналитики',
    prosecutor: 'Военная прокуратура Томского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Алексей Буров',
    phone: '+7 (3822) 41-27-73',
    personnel: 620,
    readiness: 83,
    status: 'плановая подготовка',
    lastInspection: '05.03.2026'
  },
  {
    id: '70007',
    name: 'в/ч 70007',
    districtKey: 'siberian',
    district: 'Сибирский федеральный округ',
    city: 'Улан-Удэ',
    lat: 51.8334,
    lng: 107.584,
    garrison: 'Улан-Удэнский гарнизон',
    specialization: 'авиационное техобслуживание',
    prosecutor: 'Военная прокуратура Улан-Удэнского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Никита Жданов',
    phone: '+7 (3012) 55-70-43',
    personnel: 700,
    readiness: 85,
    status: 'стабильный режим',
    lastInspection: '26.01.2026'
  },
  {
    id: '80006',
    name: 'в/ч 80006',
    districtKey: 'far-eastern',
    district: 'Дальневосточный федеральный округ',
    city: 'Комсомольск-на-Амуре',
    lat: 50.5499,
    lng: 137.0079,
    garrison: 'Комсомольский гарнизон',
    specialization: 'авиационно-ремонтная база',
    prosecutor: 'Военная прокуратура Комсомольского гарнизона',
    curatorRank: 'подполковник юстиции',
    curatorName: 'Виктор Захаров',
    phone: '+7 (4217) 54-18-06',
    personnel: 650,
    readiness: 84,
    status: 'стабильный режим',
    lastInspection: '02.02.2026'
  },
  {
    id: '80007',
    name: 'в/ч 80007',
    districtKey: 'far-eastern',
    district: 'Дальневосточный федеральный округ',
    city: 'Магадан',
    lat: 59.5682,
    lng: 150.8085,
    garrison: 'Магаданский гарнизон',
    specialization: 'северо-восточный узел снабжения',
    prosecutor: 'Военная прокуратура Магаданского гарнизона',
    curatorRank: 'майор юстиции',
    curatorName: 'Иван Панов',
    phone: '+7 (4132) 64-25-11',
    personnel: 500,
    readiness: 78,
    status: 'плановая подготовка',
    lastInspection: '13.02.2026'
  }
);

window.UNITS_DATA = window.UNITS_DATA.map((unit) => ({
  ...unit,
  rank:
    unit.rank ||
    (unit.curatorRank ? unit.curatorRank.charAt(0).toUpperCase() + unit.curatorRank.slice(1) : ''),
  fio: unit.fio || unit.curatorName || ''
}));
